title:              Klue QA Rival
email:              klueau
description:        Klue QA Rival
author:             KlueQA
baseurl:            ""
url:                "https://klue-qa-test-rival.github.io"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
